CREATE OR REPLACE VIEW v_forecast_ALL AS 
SELECT
    forecast.id,
    forecast.account_id,
    ACCOUNT.fullName AS account_name,
    agency.name AS name_of_agency,
    CLIENT.name AS name_of_client,
    client_type.name AS name_of_client_type,
    process.name AS process_name,
    forecast.ptt_weekly_update,
    forecast.remark,
    forecast.potential,
    FORMAT(forecast.SGD1, 0) AS SGD1,
    FORMAT(forecast.RCC1, 0) AS RCC1,
    FORMAT(forecast.PTT1, 0) AS PTT1,
    FORMAT(forecast.PRO1, 0) AS PRO1,
    FORMAT(forecast.SGD2, 0) AS SGD2,
    FORMAT(forecast.RCC2, 0) AS RCC2,
    FORMAT(forecast.PTT2, 0) AS PTT2,
    FORMAT(forecast.PRO2, 0) AS PRO2,
    FORMAT(forecast.SGD3, 0) AS SGD3,
    FORMAT(forecast.RCC3, 0) AS RCC3,
    FORMAT(forecast.PTT3, 0) AS PTT3,
    FORMAT(forecast.PRO3, 0) AS PRO3,
    FORMAT(forecast.SGD4, 0) AS SGD4,
    FORMAT(forecast.RCC4, 0) AS RCC4,
    FORMAT(forecast.PTT4, 0) AS PTT4,
    FORMAT(forecast.PRO4, 0) AS PRO4,
    FORMAT(forecast.SGD5, 0) AS SGD5,
    FORMAT(forecast.RCC5, 0) AS RCC5,
    FORMAT(forecast.PTT5, 0) AS PTT5,
    FORMAT(forecast.PRO5, 0) AS PRO5,
    FORMAT(forecast.SGD6, 0) AS SGD6,
    FORMAT(forecast.RCC6, 0) AS RCC6,
    FORMAT(forecast.PTT6, 0) AS PTT6,
    FORMAT(forecast.PRO6, 0) AS PRO6,
    FORMAT(forecast.SGD7, 0) AS SGD7,
    FORMAT(forecast.RCC7, 0) AS RCC7,
    FORMAT(forecast.PTT7, 0) AS PTT7,
    FORMAT(forecast.PRO7, 0) AS PRO7,
    FORMAT(forecast.SGD8, 0) AS SGD8,
    FORMAT(forecast.RCC8, 0) AS RCC8,
    FORMAT(forecast.PTT8, 0) AS PTT8,
    FORMAT(forecast.PRO8, 0) AS PRO8,
    FORMAT(forecast.SGD9, 0) AS SGD9,
    FORMAT(forecast.RCC9, 0) AS RCC9,
    FORMAT(forecast.PTT9, 0) AS PTT9,
    FORMAT(forecast.PRO9, 0) AS PRO9,
    FORMAT(forecast.SGD10, 0) AS SGD10,
    FORMAT(forecast.RCC10, 0) AS RCC10,
    FORMAT(forecast.PTT10, 0) AS PTT10,
    FORMAT(forecast.PRO10, 0) AS PRO10,
    FORMAT(forecast.SGD11, 0) AS SGD11,
    FORMAT(forecast.RCC11, 0) AS RCC11,
    FORMAT(forecast.PTT11, 0) AS PTT11,
    FORMAT(forecast.PRO11, 0) AS PRO11,
    FORMAT(forecast.SGD12, 0) AS SGD12,
    FORMAT(forecast.RCC12, 0) AS RCC12,
    FORMAT(forecast.PTT12, 0) AS PTT12,
    FORMAT(forecast.PRO12, 0) AS PRO12,
    FORMAT(forecast.total_SGD, 0) AS total_SGD,
    FORMAT(forecast.total_RCC, 0) AS total_RCC,
    FORMAT(forecast.total_PTT, 0) AS total_PTT,
    FORMAT(forecast.total_PRO, 0) AS total_PRO,
    FORMAT(forecast.total, 0) AS total,
    forecast.year,
    process.id AS process_id
FROM
    forecast,
    ACCOUNT,
    agency,
    CLIENT,
    client_type,
    process
WHERE
    forecast.agency_id = agency.id AND forecast.client_id = CLIENT.id AND forecast.account_id = ACCOUNT.id AND forecast.client_type_id = client_type.id AND forecast.process_id = process.id